=== technomunk/technomunk.github.io/content/assignment.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Assignment",
    "description": "A professional assignment schema for a role",
    "definitions": {
        "shortDate": {
            "type": "string",
            "pattern": "^(\\d{4}-\\d{2}|today)$"
        }
    },
    "properties": {
        "$schema": {
            "type": "string"
        },
        "title": {
            "type": "string",
            "description": "Held title"
        },
        "employer": {
            "type": "string",
            "description": "Name of the employer"
        },
        "description": {
            "type": "string",
            "description": "Description of the role and responsibilities"
        },
        "startDate": {
            "$ref": "#/definitions/shortDate",
            "description": "Start date of the assignment"
        },
        "endDate": {
            "$ref": "#/definitions/shortDate",
            "description": "End date of the assignment"
        },
        "skills": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Skills used or acquired during the assignment"
        }
    },
    "additionalProperties": false
}

=== technomunk/technomunk.github.io/content/assignments/vyer_fullstack.json
{
    "$schema": "../assignment.schema.json",
    "title": "Fullstack Developer",
    "employer": "Vyer",
    "description": "Focus on extending the WebGL-backed 3D viewer with new features and functionality, as well as maintaining the existing codebase. This includes working on both the frontend and backend components of the application, ensuring a seamless user experience and robust performance.",
    "startDate": "2025-04",
    "endDate": "today",
    "skills": [
        "css",
        "git",
        "glsl",
        "GraphQL",
        "html",
        "linux",
        "Material_UI",
        "PostgreSQL",
        "React",
        "Three.js",
        "TypeScript",
        "WebGL"
    ]
}

=== technomunk/technomunk.github.io/content/assignments/billogram_integration.json
{
    "$schema": "../assignment.schema.json",
    "title": "Integration Developer",
    "employer": "Billogram",
    "description": "Maintenance and development of file integrations towards customers that are not able to make use of the core product API. My responsabilities primarily consisted of solution design and architecture, implementation, testing and quality assurance of the integrations as any augmentations to the core product to fit customer needs.",
    "startDate": "2021-08",
    "endDate": "2023-08",
    "skills": [
        "Python",
        "git",
        "AWS",
        "DynamoDB",
        "SNS",
        "SQS",
        "S3",
        "HTTP",
        "REST",
        "Microservices",
        "Iterative_Development",
        "Agile",
        "DDD",
        "TDD",
        "linux"
    ]
}

=== technomunk/technomunk.github.io/content/assignments/ths_armada_backend_developer.json
{
    "$schema": "../assignment.schema.json",
    "title": "Backend Developer",
    "employer": "THS Armada",
    "description": "Backend development for the annual career fair at KTH, as well as the associated app. Primary responsabilities consisted of designing and developing features requested by recruiters at the fair. The highlight was designing the backend and frontend interaction between existing backend servers and a brand new mobile app for that year.",
    "startDate": "2017-04",
    "endDate": "2017-10",
    "skills": [
        "Python",
        "Django",
        "git",
        "WireShark",
        "HTTP",
        "Postman"
    ]
}

=== technomunk/technomunk.github.io/content/assignments/billogram_sr_integration.json
{
    "$schema": "../assignment.schema.json",
    "title": "Senior Integration Developer",
    "employer": "Billogram",
    "description": "Guiding, tutoring and assisting the team to ensure the maintenance and delivery of file integrations towards customers that are not able to make use of the core product API. My responsabilities primarily consisted of facilitating the team member's technical growth. Incoming work prioritization, wholistic design and architecture. Implementation, testing and quality assurance of the integrations as any augmentations to the core product to fit customer needs.",
    "startDate": "2023-08",
    "endDate": "2025-04",
    "skills": [
        "Python",
        "git",
        "AWS",
        "DynamoDB",
        "SNS",
        "SQS",
        "S3",
        "HTTP",
        "REST",
        "Microservices",
        "Iterative_Development",
        "Agile",
        "DDD",
        "TDD",
        "Jira",
        "GitHub_Actions",
        "K8S",
        "Mermaid",
        "linux"
    ]
}

=== technomunk/technomunk.github.io/content/assignments/mutate_developer.json
{
    "$schema": "../assignment.schema.json",
    "title": "Developer",
    "employer": "Mutate",
    "description": "Research and development of a game engine as well as a user generated content platform. My responsabilities primarily consisted of developing new functionality. Designing, implementing, testing and optimizing core systems and tools. Highlights include game loop, netcode (including physics synchronization), world building and asset processing tooling, dynamic off-grid voxel physics, entire animation system as well as procedural animation, third party scripting framework development, backend rework and delivery optimization.",
    "startDate": "2019-05",
    "endDate": "2021-01",
    "skills": [
        "C++",
        "x86asm",
        "csharp",
        "GLSL",
        "Vulkan",
        "Clang",
        "MSVC",
        "git",
        "VTune",
        "Conan",
        "AWS",
        "KMS",
        "UDP",
        "TCP",
        "HTTP",
        "Procedural_Animation",
        "Performance_Tuning",
        "GPGPU",
        "linux",
        "windows"
    ]
}
