=== technomunk/technomunk.github.io/content/project.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Project",
    "description": "A hobby project schema",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "title": {
            "type": "string",
            "description": "The title of the project"
        },
        "description": {
            "type": "string",
            "description": "A brief description of the project"
        },
        "aspiration": {
            "type": "string",
            "description": "The aspiration or goal of the project"
        },
        "skills": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Technologies used in the project"
        },
        "lastActivity": {
            "type": "string",
            "format": "date",
            "description": "The date of the last activity on the project"
        },
        "status": {
            "type": "string",
            "description": "The current status of the project, e.g., 'Active', 'Inactive', 'Sporadically active'"
        }
    },
    "additionalProperties": false
}

=== technomunk/technomunk.github.io/content/projects/gengine.json
{
    "$schema": "../project.schema.json",
    "title": "GEngine",
    "description": "Game engine written in C++ with Vulkan as the graphics API. I ran out of steam after implementing basic scene organization and rendering logic.",
    "aspiration": "Learn Vulkan (and modern graphics APIs) and game engine development",
    "skills": [
        "c++",
        "vulkan",
        "glsl",
        "windows"
    ],
    "lastActivity": "2018-10-17",
    "status": "Abandoned"
}

=== technomunk/technomunk.github.io/content/projects/gnet.json
{
    "$schema": "../project.schema.json",
    "title": "GNET",
    "description": "Message-based networking library for real-time applications, supporting reliable out-of-order delivery mixed with unreliable best-effort delivery, congestion avoidance, rate-limitting and bit-packing over UDP.",
    "aspiration": "Dive deep into networking and create something I could use for future projects.",
    "skills": [
        "c++",
        "udp",
        "posix",
        "rust"
    ],
    "lastActivity": "2021-08-15",
    "status": "Completed C++ version, Rust-rewrite abandoned"
}

=== technomunk/technomunk.github.io/content/projects/exploramap.json
{
    "$schema": "../project.schema.json",
    "title": "Exploramap App",
    "description": "Exploration gamification cross-platform application based on GPS and OpenStreetMap data.",
    "aspiration": "Dive into mobile and cross-platform development. Focus on design and user experience and build something that could evolve into a side-business.",
    "skills": [
        "android",
        "dart",
        "flutter",
        "github_actions",
        "glsl",
        "gradle",
        "kotlin",
        "notion"
    ],
    "lastActivity": "2024-01-25",
    "status": "Semi-active"
}

=== technomunk/technomunk.github.io/content/projects/misc.json
{
    "$schema": "../project.schema.json",
    "title": "Miscellaneous",
    "description": "I regularly write quick solutions or implement random ideas I get. This can be prototyping an idea that leads to a project (for example the cookbook server or the exploramap app), brainstorming a solution to a problem (voxelization, working out algebra), playing a coding-centric game (Screeps AI, bitburner, Farmer Was Replaced), contributing to an open source project with a bugfix or a minor feature improvement or just trying to entertain myself. These are too numerous and too small to list in detail.",
    "aspiration": "Self-entertainment, experimentation or solving a problem specific to me.",
    "skills": [
        "c",
        "c++",
        "rust",
        "mipsasm",
        "x86asm",
        "bespoke_assembly",
        "lua",
        "javascript",
        "java",
        "typescript",
        "erlang",
        "elixir",
        "python",
        "fishshell"
    ],
    "lastActivity": "2000-10-10",
    "status": "Sporadically active"
}

=== technomunk/technomunk.github.io/content/projects/website.json
{
    "$schema": "../project.schema.json",
    "title": "Technomunk Website",
    "description": "This very website you're viewing right now",
    "aspiration": "Create something that is easily shareable that I can continuously build up over many years. Additionally learn finishing projects when they are good enough instead of getting stuck trying to perfect one.",
    "skills": [
        "typescript",
        "sass",
        "astrojs",
        "vitejs"
    ],
    "lastActivity": "2024-03-18",
    "status": "Active"
}

=== technomunk/technomunk.github.io/content/projects/bottica.json
{
    "$schema": "../project.schema.json",
    "title": "Bottica: the sassy discord bot",
    "description": "A personal discord bot, providing entertainment on mine and my friends' servers.",
    "aspiration": "Work on a small-scope project, focusing on quick delivery and user experience. Additionally work on my user experience design skills.",
    "skills": [
        "python",
        "discord_api"
    ],
    "lastActivity": "2023-07-15",
    "status": "Completed"
}

=== technomunk/technomunk.github.io/content/projects/aoc.json
{
    "$schema": "../project.schema.json",
    "title": "Advent of code participation",
    "description": "Regular participation in the annual advent-of-code event.",
    "aspiration": "Get an opportunity to learn a brand new programming language every year as well as keep my problem solving skills sharp.",
    "skills": [
        "julia",
        "clojure",
        "erlang",
        "python"
    ],
    "lastActivity": "2023-12-25",
    "status": "Event-based activity"
}

=== technomunk/technomunk.github.io/content/projects/cookbook.json
{
    "$schema": "../project.schema.json",
    "title": "Cookbook",
    "description": "System-driven recipe server supporting actual cookie recipes as well as other recipe-based domains (games, production lines, etc).",
    "aspiration": "Started as a way to explore the Go language, but was abandoned when I realized Go was not well-suited for the project.",
    "skills": [
        "golang",
        "javascript"
    ],
    "lastActivity": "2022-06-15",
    "status": "Abandoned (for now)"
}
