=== technomunk/technomunk.github.io/content/project.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Project",
    "description": "A hobby project schema",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "title": {
            "type": "string",
            "description": "The title of the project"
        },
        "description": {
            "type": "string",
            "description": "A brief description of the project"
        },
        "aspiration": {
            "type": "string",
            "description": "The aspiration or goal of the project"
        },
        "skills": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Technologies used in the project"
        },
        "lastActivity": {
            "type": "string",
            "format": "date",
            "description": "The date of the last activity on the project"
        },
        "status": {
            "type": "string",
            "description": "The current status of the project, e.g., 'Active', 'Inactive', 'Sporadically active'"
        }
    },
    "additionalProperties": false
}

=== technomunk/technomunk.github.io/content/projects/trains.json
{
    "$schema": "../project.schema.json",
    "title": "Trains!",
    "description": "A game strongly inspired by Sid Mier's Railroads, written from scratch using C++ standard library and OpenGL. Highlights included writing a bespoke SIMD-optimized linear algebra library. Unfortunately the project died due to a drive failure and I did not use a version control system at the time.",
    "aspiration": "Learn graphics processing and game development.",
    "skills": [
        "C++",
        "OpenGL",
        "GLSL",
        "x86asm",
        "windows"
    ],
    "lastActivity": "2017-06-17",
    "status": "Dead due to lost source code"
}

=== technomunk/technomunk.github.io/content/projects/create_mod.json
{
    "$schema": "../project.schema.json",
    "title": "A minecraft mod",
    "description": "Minecraft mod adding more blocks to the base game with custom hitboxes and graphical effects. Culminanted in data-driven generation system where users could add new blocks with custom looks, properties and hitboxes by creating a json file. The idea became redundant once Minecraft 1.0 was released along with more powerful resource-packs.",
    "aspiration": "Learn collaborative programming and working with end-users.",
    "skills": [
        "java"
    ],
    "lastActivity": "2014-07-20",
    "status": "Redundant"
}
